# Hugo variables
#
baseurl = "https://www.noschangements.fr/"
languageCode = "fr-FR"
DefaultContentLanguage = "fr"
title = "NosChangements"
theme = "noschangements-theme"
enableRobotsTXT=true
enableGitInfo=true
removePathAccents = true

# number of posts to show on home/category/tag pages (Default: 10)
paginate = 10

# optionally override the site's footer with custom copyright text
copyright = "Sauf mention contraire, le contenu de ce site est sous licence [Creative Commons BY-NC-SA](https://creativecommons.org/licenses/by-nc-sa/4.0/deed.fr)"

googleAnalytics = "UA-124096389-1"
#disqusShortname = "XYW"

#[[menu.navbar]]
#  name = "A propos"
#  url = "/about/"

# Theme variables
#
[params]
  # Site author
  author = "Camille Roux"

  # Description/subtitle for homepage (can be Markdown)
  description = "Parlons de nos changements et de nos remises en question. Le tout sans jugement, sans culpabilisation, sans critique... "

  footerText = "Créé par [Camille Roux](https://www.camilleroux.com/) </br> Sauf mention contraire, le contenu de ce site est sous licence [Creative Commons BY-NC-SA](https://creativecommons.org/licenses/by-nc-sa/4.0/deed.fr)"

  # Format dates with Go's time formatting
  date_format = "02/01/2006"

  # verification string for Google Webmaster Tools
  google_verify_meta = "P0tpRN2wi4n01OB0LzhkX_hKKOcO9lo9ntd-buXM4kU"

  # verification string for Bing Webmaster Tools
  #bing_verify_meta = "3DA353059F945D1AA256B1CD8A3DA847"

  # verification string for Yandex Webmaster Tools
  #yandex_verify_meta = "66b077430f35f04a"

  # Optionally display a message about the site's use of cookies, which may be
  # required for your site in the European Union. Set the parameter below to a
  # page where the user can get more information about cookies, either on your
  # site or externally, for example:
  #cookie_consent_info_url = "/cookie-information/"
  #cookie_consent_info_url = "http://cookiesandyou.com"

  # show sharing icons on pages/posts (default: true)
  sharingicons = false

  # Disable the use of sub-resource integrity on CSS/JS assets (default: false)
  # Useful if you're using a CDN or other host where you can't control cache headers
  disable_sri = true

  [params.social]
    # Optional, used for attribution in Twitter cards (ideally not a person
    # for example: nytimes, flickr, NatGeo, etc).
    # See: https://dev.twitter.com/cards/types/summary-large-image
    twitter = "camilleroux"

# Default content language for Hugo 0.17's multilingual support (default is "en")
# See: https://github.com/spf13/hugo/blob/master/docs/content/content/multilingual.md
# DefaultContentLanguage = "fr"

# Languages to render
[languages.fr]
  [languages.fr.Taxonomies]
    category = "categories"
    tag = "tags"
#[languages.bg]

# vim: ts=2 sw=2 et